language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: FYS5VbJlmyPSGT7R2ZSuMxhMxRCtTVQ2LgDjljcnODucXxqnGtfDjPv0WpT9a4XSU9Dj5C+I3LSr90oeMBaV+BpHbcU6cmOxnp1j2Qcuc7eXx9QmnJibqZi7PsVqqYHmVydLGHkTped0gE0wC9s5ArBTKjq3+zVgi95T6pcJDDYttU5lpDmASdK7rBHauRMA/PkqVxvswsSM05rjrR1X+aLdMv8TYZuJqMBK46pUIFDZpLxnWN/mv4AT0Kps0KFdq9nPZweewRnslxWMPSbPopoCmuNqn0pTiD/8L6Ha6DLC8vxwBgjfn+dL0UeM4fpGj55Z4Vn1+3Qro7dKY48OXghsGJo0AJYHVQP1KtrlNnGmrVDS1jqGFN/zEW2q6/2ZF8GIax1Rp62JeG555Ei9S+rug9/N8Fck8qkWgpS+krwMxKz3roE2Zhxzxr4KF6y+Y28QhVppcJcEf81d3SIIXGXA55L7OxPu5vfsSDXA+4l9tMCJp1fKsR82nN9nJR6kr74R0vpYF4lvnyDlS1BAA2U5GwsPRTfDMHBi5/GnXhpHcodmMj5YFdAn7Lpy8YjZmyDWITsSFePqfXxmnWMNoQsSHdl1uAS91pLfDuF1jGpUsur0U9jON2BNM19CJTpECUiGv4cYS6mVIl+dRruG7l2r5jcMouav/n5MSobMQ6U=
  app: mysterious-meadow-43570
